dist: bionic
language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
  - 'npm start & ./node_modules/.bin/wait-on http://localhost:3000'
  - npm run cy:run
after_success:
  - codecov
